GET http://127.0.0.1:8809/connect
User-Agent: ArcadePlus/0.5.3
Accept: application/json

###

POST http://127.0.0.1:8809/generate
Content-Type: application/json

{
  "id": "arctapjump",
  "args": {
    "globalOffset": 36000,
    "fps": 50,
    "bpm": 100.0,
    "timingStart": 0,
    "timingEnd": 1000,
    "positionStart": [
      0.25,
      0.00
    ],
    "positionEnd": [
      0.00,
      1.00
    ],
    "showFirstFrame": false,
    "control": "0:2000"
  }
}

###

POST http://127.0.0.1:8809/generate
Content-Type: application/json

{
  "id": "example",
  "args": {
    "timingList": [
      78095,
      78571
    ]
  }
}

###

POST http://127.0.0.1:8809/generate
Content-Type: application/json

{
  "id": "voltagetransformer",
  "args": {
    "chart": "arc(600,750,0.00,0.00,s,0.80,0.00,0,none,false);\r\narc(750,1200,0.00,0.00,s,0.00,0.00,0,none,false);\r\narc(1200,1350,0.50,0.50,s,0.80,0.00,1,none,false);\r\narc(1350,1800,0.50,0.50,s,0.00,0.00,1,none,false);\r\narc(1800,1950,1.00,1.00,s,0.80,0.00,0,none,false);\r\narc(1950,2400,1.00,1.00,s,0.00,0.00,0,none,false);\r\narc(3000,3150,1.00,1.00,s,0.80,0.00,1,none,false);\r\narc(3150,3600,1.00,1.00,s,0.00,0.00,1,none,false);\r\narc(3600,3750,0.50,0.50,s,0.80,0.00,0,none,false);\r\narc(3750,4200,0.50,0.50,s,0.00,0.00,0,none,false);\r\narc(4200,4350,0.00,0.00,s,0.80,0.00,1,none,false);\r\narc(4350,4800,0.00,0.00,s,0.00,0.00,1,none,false);\r\narc(5400,5550,0.50,0.50,s,0.80,0.00,0,none,false);\r\narc(5550,7200,0.50,0.50,s,0.00,0.00,0,none,false);"
  }
}
